name: CI - Automation Testing (UI Web)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle (Official & Stable)
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Install Microsoft Edge
        run: |
        wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
        sudo apt update
        sudo apt install microsoft-edge-stable

      - name: Run UI Tests
        run: ./gradlew clean test -Dheadless=true

      - name: Wait & Upload Cucumber HTML Report
        if: always()
        run: |
          # Tunggu sampai report pasti muncul (max 10 detik)
          for i in {1..20}; do
            if [ -f build/reports/cucumber/html/index.html ]; then
              echo "Laporan Cucumber ditemukan!"
              break
            fi
            echo "Menunggu laporan... ($i/20)"
            sleep 0.5
          done
          echo "Upload artifact report..."
        shell: bash

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: build/reports/cucumber/html/
          retention-days: 30

      - name: Upload Test Results (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: build/test-results/test/
